### ISSUE TITLE
IndentationError: expected an indented block

### ISSUE THREAD

**Issue by JoshBerry022** [sogbesano/multiple-knapsack-problem#3]
```
Traceback (most recent call last):
  File "mkp.py", line 2, in <module>
    from parser import RcParser, ItemParser, KnapsackParser
  File "/projects/clones/multiple-knapsack-problem/parser.py", line 3, in <module>
    from item import Item
  File "/projects/clones/multiple-knapsack-problem/item.py", line 9
    return 'i = {0}, p = {1}, w = {2}'.format(self.index, self.profit, self.weight)
         ^
IndentationError: expected an indented block
```

I am running 
Python 3.6.3 |Anaconda custom (64-bit)| (default, Nov  3 2017, 12:34:11)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin

**Comment by sogbesano** [comment]
Issue fixed by @MarkusMichaelRau
